openapi: 3.0.2
info:
  title: STARMINE API
  version: 0.0.1
  description: STARMINEで利用するAPIを記載する
servers:
  - url: 'http://localhost:8083/'
paths:
  /images/{uuid}:
    get:
      summary: 画像の一覧のURLを取得する
      operationId: listImages
      tags:
        - images
      parameters:
        - name: uuid
          in: path
          description: 画像を取得するユーザのID
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: 1回で取得できる画像の枚数
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 画像一覧の集合を返す
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Images'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/images/{uuid}/category/{category}':
    get:
      summary: 画像の特定のカテゴリのURLを取得する
      operationId: listImageByCategory
      tags:
        - images
      parameters:
        - name: uuid
          in: path
          description: 画像を取得するユーザのID
          required: true
          schema:
            type: string
        - name: category
          in: path
          description: 画像取得対象のカテゴリーの名前
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: 1回で取得できる画像の枚数
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Images'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/images/{uuid}/tag/{tag}':
    get:
      summary: 画像の特定のタグのURLを取得する
      operationId: listImageByTag
      tags:
        - images
      parameters:
        - name: uuid
          in: path
          description: 画像を取得するユーザのID
          required: true
          schema:
            type: string
        - name: tag
          in: path
          description: 画像取得対象のタグの名前
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: 1回で取得できる画像の枚数
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Images'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Image:
      required:
        - uuid
        - url
        - category
        - tags
      properties:
        uuid:
          type: string
        name:
          type: string
        category:
          type: string
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
    Images:
      type: array
      items:
        $ref: '#/components/schemas/Image'
    Tag:
      required: name
      properties:
        name:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
